module.exports = {
<<<<<<< Updated upstream
  generalSidebar: [
    {
      type: 'autogenerated',
      dirName: 'general', // means 'docs/general/' directory
    }
  ]
=======
  docsSidebar: {
    Deployment: [
      'deployment/guide',
      'deployment/troubleshooting',
      'deployment/browsers-and-cookies'
    ],
    Translation: [
      'translation/guide'
    ],
    "Election Testing": [
      'testing/e2e'
    ],
    "Advanced Topics": [
      'advanced-elections/introduction',
      'advanced-elections/election-creation',
      'advanced-elections/parent-and-children-elections',
      'advanced-elections/write-ins',
      'advanced-elections/authentication-timeouts',
      'advanced-elections/electoral-board-ceremonies'
    ],
    Integrations: [
      'integrations/smart-link-auth'
    ],
    Contribute: [
      'contribute/guide',
      'contribute/release-lifecycle',
      'contribute/release-howto'
    ]
  },
  fileFormatsSidebar: {
    'File Formats': [
      'file-formats/introduction',
      'file-formats/ballot-encoding',
      'file-formats/election-creation-json',
    ]
  }
>>>>>>> Stashed changes
};
