[
  {
    "title": "New election",
    "description": "This is the description of the election. You can add simple html like <strong>bold</strong> or <a href=\"https://sequentech.io\">links to websites</a>.\n\n<br><br>You need to use two br element for new paragraphs.",
    "authorities": [
      "votular-prod-auth2"
    ],
    "director": "votular-prod-auth1",
    "presentation": {
      "theme": "default",
      "share_text": [
        {
          "network": "Twitter",
          "button_text": "",
          "social_message": "I have just voted in election __URL__, you can too! #sequent"
        },
        {
          "network": "Facebook",
          "button_text": "",
          "social_message": "__URL__"
        }
      ],
      "urls": [],
      "theme_css": ""
    },
    "layout": "simple",
    "num_successful_logins_allowed": 0,
    "tallyPipesConfig": {
      "version": "1.0",
      "pipes": [
        {
          "type": "tally_pipes.pipes.pdf.configure_pdf",
          "params": {
            "languages": ["en"]
          }
        },
        {
          "type": "tally_pipes.pipes.results.do_tallies",
          "params": {}
        },
        {
          "type": "tally_pipes.pipes.sort.sort_non_iterative",
          "params": {}
        }
      ]
    },
    "has_ballot_boxes": false,
    "census": {
      "voters": [],
      "auth_method": "email",
      "census": "close",
      "extra_fields": [
        {
          "must": true,
          "name": "email",
          "type": "email",
          "required": true,
          "min": 2,
          "max": 200,
          "required_on_authentication": true
        }
      ],
      "admin_fields": [
        {
          "name": "org_legal_name",
          "label": "Organization: Legal Name",
          "description": "Required. Please provide the name under which your organization is legally registered. It will be shown as part of the public information in a section inside the election public page.",
          "placeholder": "Example: Association of Surgeons of Great Britain",
          "min": 1,
          "max": 255,
          "value": "Example Organization Name",
          "required": true,
          "private": true,
          "type": "text"
        },
        {
          "name": "org_url",
          "label": "Organization: Website URL",
          "description": "Optional. Please provide the URL of your organization. It will be shown as part of the public information in a section inside the election public page.",
          "placeholder": "Example: https://example.com",
          "min": 5,
          "value": "https://example.com",
          "required": false,
          "private": true,
          "type": "text"
        },
        {
          "name": "org_legal_id",
          "label": "Organization: VAT Id Number",
          "description": "Optional. Please provide the Value Added Tax (VAT) identification number under which your organization is legally registered. It will be shown as part of the public information in a section inside the election public page.",
          "placeholder": "Example: X1234567",
          "min": 5,
          "value": "EXAMPLE_VAT_ID",
          "required": false,
          "type": "text"
        },
        {
          "name": "org_legal_contact",
          "label": "Organization: Email Legal Contact",
          "description": "Optional. Please provide a way for voters and other actors to contact for legal matters. It will be shown as part of the public information in a section inside the election public page.",
          "placeholder": "Example: contact@example.com",
          "value": "contact@example.com",
          "required": false,
          "private": true,
          "type": "text"
        },
        {
          "name": "election_legal_notice",
          "label": "Election: Legal Notice",
          "description": "Optional. Please add any legal notice required to be shown to voters by the law of your country. It will be shown as part of the public information in a section inside the election public page.",
          "placeholder": "",
          "value": "This is an example legal notice. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem.\n\nLorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem.",
          "required": false,
          "private": true,
          "type": "textarea"
        },
        {
          "name": "election_support_text",
          "label": "Election: Voters Support Text",
          "description": "Optional. Please add a text explaining voters how to reach you for support. Consider to include means of contact with your support team and the support hours schedule.",
          "placeholder": "",
          "value": "This is an example support text. Contact us a contact@example.com or call to +44 6666 666 666",
          "required": false,
          "private": true,
          "type": "textarea"
        }
      ],
      "config": {
        "allow_user_resend": true,
        "msg": "Vote in __URL__ with code __CODE__",
        "subject": "Vote now with Sequent",
        "authentication-action": {
          "mode": "vote",
          "mode-config": {
            "url": ""
          }
        },
        "registration-action": {
          "mode": "vote",
          "mode-config": null
        }
      }
    },
    "questions": [
      {
        "answer_total_votes_percentage": "over-total-valid-votes",
        "answers": [
          {
            "category": "",
            "details": "This is an option with an simple example description.",
            "id": 0,
            "sort_order": 0,
            "text": "Example option 1",
            "urls": [
              {
                "title": "URL",
                "url": ""
              },
              {
                "title": "Image URL",
                "url": ""
              }
            ]
          },
          {
            "category": "",
            "details": "An option can contain a description. You can add simple html like <strong>bold</strong> or <a href=\"https://sequentech.io\">links to websites</a>. You can also set an image url below, but be sure it's HTTPS or else it won't load.\n\n<br><br>You need to use two br element for new paragraphs.",
            "id": 1,
            "sort_order": 1,
            "text": "Example option 2",
            "urls": [
              {
                "title": "URL",
                "url": "https://sequentech.io"
              },
              {
                "title": "Image URL",
                "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/The_Fabs.JPG/220px-The_Fabs.JPG"
              }
            ]
          },
          {
            "category": "",
            "details": "",
            "id": 2,
            "sort_order": 2,
            "text": "Example option 3",
            "urls": [
              {
                "title": "URL",
                "url": ""
              },
              {
                "title": "Image URL",
                "url": ""
              }
            ]
          }
        ],
        "description": "This is the description of this question. You can have multiple questions. You can add simple html like <strong>bold</strong> or <a href=\"https://sequentech.io\">links to websites</a>.\n\n<br><br>You need to use two br element for new paragraphs.",
        "layout": "accordion",
        "max": 1,
        "min": 1,
        "num_winners": 1,
        "tally_type": "plurality-at-large",
        "title": "Test question title",
        "extra_options": {
          "shuffle_categories": true,
          "shuffle_all_options": true,
          "shuffle_category_list": [],
          "show_points": false
        },
        "active": true
      }
    ],
    "extra_data": {}
  }
]
